batch_size = 32
epochs = 200
lr = 0.001
momentum = 0.9
no_cuda =False
cuda_id = '0'
seed = 1
log_interval = 20
l2_decay = 5e-4
class_num = 9
param = 0.3
bottle_neck = True
root_path = r"E:\工作文档\DATA\office31\\"
source_name = "FFT0"
target_name = "FFT1"
